# -*- coding: utf-8 -*-
"""PRODUCT REVIEW

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_U122MASFXl2_8gxA_inko8KDDa7iiN
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

from pandas.core.api import DataFrame
sentiment =pipeline("sentiment-analysis")
reviews=""" the product is good for all types of skin.
But the cost is not budjet frriendly.
It shows the results quickly.
BUt the quantity is not related to the cost.
Overall it is a good skin but not the cost friendly product.
"""
sentences = reviews.split(".") # Clean up sentences and remove empty strings
pros = []
cons = []
for s in sentences:
  s=s.strip()
  if s== "":
    continue
  result = sentiment(s)[0] # Fixed 'o' to '0'
  if result["label"]=="POSITIVE":
    pros.append(s)
  elif result["label"]=="NEGATIVE":
    cons.append(s)

# These lines were incorrectly indented, moved them outside the loop
pros=pros[:2]
cons=cons[:2]
df=pd.DataFrame({ # Fixed comma to dot
    "pros":pros,
    "cons":cons
    })
df