# -*- coding: utf-8 -*-
"""SENTENCE SIMILARITY

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14u4Dw3HWojFpHcjqKZXDlNDSCHNgx6q7
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')
text1 = input("Enter the text 1: ")
text2 = input("Enter the text 2: ")
embedding1 = model.encode(text1, convert_to_tensor=True)
embedding2 = model.encode(text2, convert_to_tensor=True)
similarity =  util.cos_sim(embedding1,embedding2)
print("\nsimilarity score:",round(float(similarity),2))
if similarity > 0.75:
  print("similarity level: high")
elif similarity > 0.4:
  print("similarity level: medium")
else:
  print("similarity level: Low")