# -*- coding: utf-8 -*-
"""TEXT GENERATION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lx7n9l5ISUQs_KrL0j4DC3xy8knZ383v
"""

from transformers import pipeline
notes_generator = pipeline('text-generation', model='gpt2')
chapter = input("Enter chapter name:")
prompt_notes=f"""
write detailed study notes for the chapter:
 {chapter}
 Include explanation,exmples and key points
"""
detailed_notes=notes_generator(prompt_notes,max_length=300,num_return_sequences=1)
print("\n DETAILER NOTES:\n")
print(detailed_notes[0]['generated_text'])
prompt_summary=f"""
Summarize the chapter {chapter} into one page
make it simple and exam-oriented.
"""
something = notes_generator(prompt_summary,max_length=200,num_return_sequences=1)
print("\n ONE_PAGE_SUMMARY:\n")
print(something[0]['generated_text'])
prompt_definitions = f"""
List important definitions and formulas from the chapter:
 {chapter}
      Use bullet points
      """
definitions = notes_generator(prompt_definitions, max_length=200, num_return_sequences=1)
print("\nDEFINITIONS:\n")
print(definitions[0]['generated_text'])